const allProjects = [
  {
    id: 1,
    name: "Muscle Gain",
    description:
      "A modern web application for managing gym memberships, classes, schedules, and more. Designed for gym owners, staff, and members to seamlessly interact and manage gym operations.",
    features: [
      "Member registration and login",
      "User and Admin dashboard for gym management",
      "Real time notification for user",
      "Class scheduling and booking",
      "Membership plans and payments",
      "Attendance tracking",
      "Mobile-responsive UI",
    ],
    build: "Build With Nextjs and Django rest framework",
    tech: "Nextjs, Django rest framework, PostgreSQL, Django channels, Redis, Redux",
    clientLink: "https://github.com/tanvirulislam149/gym_management_client",
    serverLink: "https://github.com/tanvirulislam149/gym_management",
    SiteLink: "https://gym-management-client-lilac.vercel.app/",
    pictures1: "https://i.ibb.co/PvzYvtjS/Screenshot-2025-06-29-121013.png",
    pictures2: "https://i.ibb.co/0NvM6cJ/Screenshot-2025-06-29-121101.png",
    pictures3: "https://i.ibb.co/35F1xZng/Screenshot-2025-06-29-121150.png",
    pictures4: "https://i.ibb.co/dsqPfJL0/Screenshot-2025-06-29-121259.png",
    demoImg: "https://i.ibb.co/PvzYvtjS/Screenshot-2025-06-29-121013.png",
  },
  {
    id: 2,
    name: "BikeParts Industries LTD",
    description:
      "This is a website about Bike parts company. This company makes some parts and deliver them to customers. Here’s a website to expand their business.",
    features: [
      "User can buy and pay for bike parts from here.",
      "Admin can manage the website.",
      "Authenticate user and admin and JWT is implemented so that others can't access website data.",
    ],
    build: "Build With MERN Stack Technology",
    tech: "React, Firebase, NodeJs, ExpressJs, MongoDB, Stripe",
    clientLink: "https://github.com/tanvirulislam149/auto-parts-client",
    serverLink: "https://github.com/tanvirulislam149/auto-parts-server",
    SiteLink: "https://bike-parts.vercel.app/",
    pictures1: "https://i.ibb.co/twMTCMnN/Screenshot-2025-06-29-120142.png",
    pictures2: "https://i.ibb.co/17FydsL/Screenshot-2023-07-08-160003.png",
    pictures3: "https://i.ibb.co/bXz4QbC/Screenshot-2023-07-08-160042.png",
    pictures4: "https://i.ibb.co/Hh4dSkt/Screenshot-2023-07-08-160140.png",
    demoImg: "https://i.ibb.co/MRpXMqw/car-0ce3d9043005d72b31ec.png",
  },
  {
    id: 2,
    name: "Creative Agency",
    description:
      "A creative agencies company which provides services that are creative like web development, web design and many more.",
    features: [
      "User can book services from here.",
      "Admin can manage the website.",
      "Authenticate user and admin",
    ],
    build: "Build With MERN Stack Technology",
    tech: "Next.js, Redux toolkit, MUI, Firebase, NodeJs, ExpressJs, MongoDB, Mongoose, Cloudinary",
    clientLink: "https://github.com/tanvirulislam149/creative-agencies",
    serverLink: "https://github.com/tanvirulislam149/creative-agencies-server",
    SiteLink: "https://creative-agencies.vercel.app/",
    pictures1: "https://i.ibb.co/bsLvTYH/Screenshot-2023-09-19-000042.png",
    pictures2: "https://i.ibb.co/ZhdWtRf/Screenshot-2023-09-19-000137.png",
    pictures3: "https://i.ibb.co/xGy5f3Y/Screenshot-2023-09-19-000209.png",
    pictures4: "https://i.ibb.co/7t2NXS6/Screenshot-2023-09-19-000233.png",
    demoImg: "https://i.ibb.co/XF0zYyL/creative-343400575d1a272f828a.jpg",
  },
  {
    id: 3,
    name: "Event Nest",
    description:
      "A Event management for organizing different events at different locations for making people's special day memorable",
    features: [
      "User, Organizer and Admin authentication.",
      "Organizing and Managing events",
      "Send email for various notification",
    ],
    build: "Build With Django",
    tech: "Django",
    clientLink: "https://github.com/tanvirulislam149/event_management_django",
    SiteLink: "https://event-management-django.onrender.com/",
    pictures1: "https://i.ibb.co/wh1yNvs9/Screenshot-2025-06-29-124307.png",
    pictures2: "https://i.ibb.co/xSFdX7VW/Screenshot-2025-06-29-124340.png",
    pictures3: "https://i.ibb.co/ZZKSN7b/Screenshot-2025-06-29-124406.png",
    pictures4: "https://i.ibb.co/6RfLXw9t/Screenshot-2025-06-29-124524.png",
    demoImg: "https://i.ibb.co/wh1yNvs9/Screenshot-2025-06-29-124307.png",
  },
];

export default allProjects;
